"""initial

Revision ID: ae71f3282012
Revises: 
Create Date: 2026-08-10 14:08:20.081255
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = 'ae71f3282012'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('req_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_project', 'audit_logs', ['project_id'], unique=False)
    op.create_index('ix_audit_req', 'audit_logs', ['req_id'], unique=False)
    op.create_index('ix_audit_ts', 'audit_logs', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_ts', table_name='audit_logs')
    op.drop_index('ix_audit_req', table_name='audit_logs')
    op.drop_index('ix_audit_project', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
